drop trigger evict_archived_products_cat_search_view_from_object_forms on products;
drop trigger evict_products_cat_search_view_from_object_forms on products;
drop function delete_inactive_products_cat_search_view_fn();
drop function toggle_products_catalog_from_to_active();
