## Orders [/v1/orders/{refNum}]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.

### View [GET]

+ Response 200 (application/json)
  + Attributes (FullOrder)

### List Shipping Methods [GET /v1/orders/{refNum}/shipping-methods]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `BR1001` (required, string) - Order reference number
+ Response 204
    + Attributes (array[ShippingMethod])

### Create [POST /v1/orders]

This route is depreciated in favor of `/v1/carts/`.

Creates a cart for an existing customer (or guest account) when `customerId`
given or creates a cart along with a new guest account when `email` is given.

+ Request (application/json)
    + Attributes (CreateCartPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Checkout [POST /v1/orders/{refNum}/checkout]

This route is depreciated in favor of `/v1/carts/`.

Place order from cart with provided reference number.

+ Parameters
    + refNum: `ABC-123` (required, string) - Cart reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Bulk Update State [PATCH /v1/orders]

+ Request (application/json)
    + Attributes (OrderBulkStateUpdatePayload)
+ Response 200 (application/json)
    + Attributes (OrderList)

### Lock [POST /v1/orders/{refNum}/lock]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Unlock [POST /v1/orders/{refNum}/unlock]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Increase Remorse Period [POST /v1/orders/{refNum}/increase-remorse-period]

Order must be in `remorseHold` state.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)

## SKU Line Items [/v1/orders/{refNum}/line-items]

### Set SKU Line Items [POST]

This route is depreciated in favor of `/v1/carts/`.

Set the number of line items. Upon completion, cart line items will match the quantities in this payload.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
+ Request (application/json)
    + Attributes (array[UpdateLineItemsPayload])
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Update SKU Line Items [PATCH]

This route is depreciated in favor of `/v1/carts/`.

Add to or remove from the number of line items that are currently stored in your cart.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
+ Request (application/json)
    + Attributes (array[UpdateLineItemsPayload])
+ Response 200 (application/json)
    + Attributes (FullOrder)

## Gift Card Line Items [/v1/orders/{refNum}/gift-cards/{code}]

### Add [POST /v1/orders/{refNum}/gift-cards]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
+ Request (application/json)
    + Attributes (GiftCardSingleCreatePayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Edit [PATCH]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
    + code: `ABC-123` (required, string) - Gift Card code.
+ Request (application/json)
    + Attributes (GiftCardSingleCreatePayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
    + code: `ABC-123` (required, string) - Gift Card code.
+ Response 200 (application/json)
    + Attributes (FullOrder)

## Credit Card Payments [/v1/orders/{refNum}/payment-methods/credit-cards]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

This route is depreciated in favor of `/v1/carts/`.

+ Request (application/json)
    + Attributes (CreditCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

This route is depreciated in favor of `/v1/carts/`.

+ Response 200 (application/json)
    + Attributes (FullOrder)

## Gift Card Payments [/v1/orders/{refNum}/payment-methods/gift-cards]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

This route is depreciated in favor of `/v1/carts/`.

+ Request (application/json)
    + Attributes (GiftCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Edit [PATCH]

This route is depreciated in favor of `/v1/carts/`.

+ Request (application/json)
    + Attributes (GiftCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE /v1/orders/{refNum}/payment-methods/gift-cards/{code}]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
    + code: `ABC-123` (required, string) - Gift card code.
+ Response 200 (application/json)
    + Attributes (FullOrder)

## Store Credit Payments [/v1/orders/{refNum}/payment-methods/store-credits]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

This route is depreciated in favor of `/v1/carts/`.

+ Request (application/json)
    + Attributes (StoreCreditPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

This route is depreciated in favor of `/v1/carts/`.

+ Response 200 (application/json)
    + Attributes (FullOrder)

## Shipping Method [/v1/orders/{refNum}/shipping-methods]

This route is depreciated in favor of `/v1/carts/`.

Shipping methods are used to describe the ways that the contents of a cart can
transported to the customer. All actions that occur against this set of
endpoints modify which shipping method is used by the cart.

### List [GET]

This route is depreciated in favor of `/v1/carts/`.

+ Response 200 (application/json)
    + Attributes (array[ShippingMethod])

### Update [PATCH]

This route is depreciated in favor of `/v1/carts/`.

Changes the shipping method to a cart.

+ Parameters
    + refNum: 1 (required, string) - Order referenceNumber
+ Request (application/json)
    + Attributes (UpdateShippingMethodPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

This route is depreciated in favor of `/v1/carts/`.

Removes the shipping method from the cart.

+ Parameters
    + refNum: 1 (required, string) - Order reference number
+ Response 204

## Shipping Address [/v1/orders/{refNum}/shipping-address]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

This route is depreciated in favor of `/v1/carts/`.

+ Request (application/json)
    + Attributes (CreateAddressPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Add By Address ID [PATCH /v1/orders/{refNum}/shipping-address/{addressId}]

This route is depreciated in favor of `/v1/carts/`.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number.
    + addressId: 1 (required, number) - Address ID.
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Update [PATCH]

This route is depreciated in favor of `/v1/carts/`.

+ Request (application/json)
    + Attributes (UpdateAddressPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

This route is depreciated in favor of `/v1/carts/`.

+ Response 200 (application/json)
    + Attributes (FullOrder)
