## Returns [/v1/returns/{refNum}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - Return reference number

### View all [GET /v1/returns]

+ Response 200 (application/json)
    + Attributes (array[Return])

### View by Customer [GET /v1/returns/customer/{customerId}]

+ Parameters
    + customerId: 1 (required, number) - Customer id
+ Response 200 (application/json)
    + Attributes (array[Return])

### View by Order [GET /v1/returns/order/{refNum}]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (array[Return])

### View [GET]

+ Response 200 (application/json)
    + Attributes (Return)

### Create [POST /v1/returns]

+ Request (application/json)
    + Attributes (ReturnCreatePayload)
+ Response 200 (application/json)
    + Attributes (Return)

### Update State [PATCH /v1/returns/{refNum}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - Return reference number
+ Request (application/json)
    + Attributes (ReturnStateUpdatePayload)
+ Response 200 (application/json)
    + Attributes (Return)

### Update Message To Customer [POST /v1/returns/{refNum}/message]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - Return reference number
+ Request (application/json)
    + Attributes (ReturnMessageToCustomerPayload)
+ Response 200 (application/json)
    + Attributes (Return)

## Return Reasons [/v1/returns/reasons]

### View all [GET]

+ Response 200 (application/json)
    + Attributes (ReturnReason)

### Create [POST]

+ Request (application/json)
    + Attributes (ReturnReasonPayload)
+ Response 200 (application/json)
    + Attributes (ReturnReason)

### Remove [DELETE /v1/returns/reasons/{reasonId}]

+ Parameters
    + reasonId: 1 (required, number) - Return reason id
+ Response 204 (application/json)

## Return Line Items [/v1/returns/{refNum}/line-items]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - Return reference number

### Add or update SKUs [POST /v1/returns/{refNum}/line-items/skus]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - Return reference number

+ Request (application/json)
    + Attributes (array[ReturnSkuLineItemPayload])
+ Response 200 (application/json)
    + Attributes (Return)

### Add [POST]

+ Request Shipping cost (application/json)
    + Attributes
        + payloadType: `shippingCost` (required, fixed) - Payload discriminator.
        + Include ReturnShippingCostLineItemPayload
+ Request SKU line item (application/json)
    + Attributes
        + payloadType: `skuItem` (required, fixed) - Payload discriminator.
        + Include ReturnSkuLineItemPayload
+ Response 200 (application/json)
    + Attributes (Return)

### Delete [DELETE /v1/returns/{refNum}/line-items/{liId}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - Return reference number
    + liId: 1 (required, number) - Line item ID
+ Response 204 (application/json)

## Return Payments [/v1/returns/{refNum}/payment-methods]

+ Parameters
    + refNum: `ABC-123` (required, string) - Return reference number

### Add or update payments [POST]

+ Request (application/json)
    + Attributes (ReturnPaymentsPayload)
+ Response 200 (application/json)
    + Attributes (Return)

### Add single payment [POST /v1/returns/{refNum}/payment-methods/{paymentMethod}]

+ Parameters
    + refNum: `ABC-123` (required, string) - Return reference number
    + paymentMethod: `giftCard` (required, enum[string]) - Payment method type
        + Members
            + `creditCard`
            + `giftCard`
            + `storeCredit`
+ Request (application/json)
    + Attributes (ReturnPaymentPayload)
+ Response 200 (application/json)
    + Attributes (Return)

### Delete single payment [DELETE /v1/returns/{refNum}/payment-methods/{paymentMethod}]

+ Parameters
    + refNum: `ABC-123` (required, string) - Return reference number
    + paymentMethod: `creditCard` (required, enum[string]) - Payment method type
        + Members
            + `creditCard`
            + `giftCard`
            + `storeCredit`
+ Response 204 (application/json)
