## Shipments

## View By Order [GET /v1/inventory/shipments/{referenceNumber}]

Gets all of the shipments associated with a single order.

+ Parameters
    + referenceNumber: `BR10001` (required, string) - Order reference number.


