build:
	@echo "--- Building \033[33mapi-js\033[0m"
	true

test:
	@echo "--- Testing \033[33mapi-js\033[0m"
	true

docker:
	@echo "--- Dockerizing \033[33mapi-js\033[0m"
	true

docker-push:
	@echo "--- Registering \033[33mapi-js\033[0m"
	true

.PHONY: build test docker docker-push
