# Data Structures

### LoginPayload
+ email: `example@example.com` (required, string) - E-mail.
+ password: `password` (required, string) - Password.
+ kind: admin (required, enum[string]) - Authorize either is admin or customer.
    + Members
        + `admin`
        + `customer`

### LoginResponse
+ id: 1 (required, number) - User ID.
+ email: `example@example.com` (required, string) - E-mail.
+ scopes: `admin` (required, array[string]) - User scopes.
+ exp: 1466079553 (required, number) - Session expiration timestamp.
+ admin: true (required, boolean) - Whether user is an admin or not.

### Region
+ id: 1 (required, number) - Unique identifier.
+ countryId: 2794 (required, number) - Country unique identifier.
+ name: `Washington` (required, string) - Region name.

### Sku
+ id: 1 (required, number) - Unique identifier.
+ name: `Flonkey` (required, string) - Product name.
+ availableForSale: false (required, boolean) - Defines where SKU is available for sale.

### Shipment
+ id: 1 (required, number) - ID.
+ orderId: 1 (required, number) - Order ID.
+ Include ShippingState
+ shippingPrice (optional, number) - Shipping price.

### ShippingState
+ shippingState: Cart (required, enum[string]) - Shipping state.
    + Members
        + `Cart`
        + `Ordered`
        + `FraudHold`
        + `RemorseHold`
        + `ManualHold`
        + `Canceled`
        + `FulfillmentStarted`
        + `Shipped`

### StoreAdminResponse
+ id: 1 (required, number) - Unique identifier.
+ name: `John Smith` (required, string) - Admin name.
+ email: `john@smith.com` (required, string) - E-mail.

### PagingMetadata
+ from:   0      (optional, number) - Start element (counting from 0) or # of elements to skip.
+ size:   10     (optional, number) - Page size.
+ pageNo: 1      (optional, number) - Page number (counting from 1).
+ total:  35	 (optional, number) - Total number of elements found.

### SortingMetadata
+ sortBy: `lastName` (optional, string) - Field to sort by (`-fieldName` for descending order).

### ResultMetadata
+ pagination 										(optional, PagingMetadata)    - Pagination metadata.
+ sorting    										(optional, SortingMetadata)   - Sorting metadata.
+ errors: `List of possible errors and warnings` 	(optional, array[string]) 	  - List of possible errors.
