# Data Structures

### AdminNote
+ id: 1 (required, number) - Unique identifier.
+ body: `Lorem ipsum` (required, string) - Note message.
+ author (required, NoteAuthor) - Note author.
+ createdAt: `2015-09-10T14:55:50Z` (required, string) - Creation date.

### NoteAuthor
+ firstName: `John` (required, string) - First name.
+ lastName: `Smith` (required, string) - Last name.
+ email: `john@smith.com` (required, string) - E-mail.

### AdminNotes (array[AdminNote])