# Data Structures

### LineItemStatus
+ status: Cart (required, enum[string]) - Line item status.
    + Members
        + `Cart`
        + `Pending`
        + `PreOrdered`
        + `BackOrdered`
        + `Canceled`
        + `Shipped`

### OrderStatus
+ orderStatus: Cart (required, enum[string]) - Order Status.
    + Members
        + `Cart`
        + `Ordered`
        + `FraudHold`
        + `RemorseHold`
        + `ManualHold`
        + `Canceled`
        + `FulfillmentStarted`
        + `Shipped`

### PaymentStatus
+ paymentStatus: Cart (optional, enum[string]) - Credit Card payment status.
    + Members
        + `Cart`
        + `Ordered`
        + `FraudHold`
        + `RemorseHold`
        + `ManualHold`
        + `Canceled`
        + `FulfillmentStarted`
        + `Shipped`

### ShippingStatus
+ shippingStatus: Cart (required, enum[string]) - Shipping status.
    + Members
        + `Cart`
        + `Ordered`
        + `FraudHold`
        + `RemorseHold`
        + `ManualHold`
        + `Canceled`
        + `FulfillmentStarted`
        + `Shipped`

### ListOrder
+ referenceNumber: `ABC-123` (required, string) - Unique identifier.
+ name: `John Smith` (optional, string) - Customer full name.
+ email: `john@smith.com` (required, string) - Customer email.
+ Include OrderStatus
+ Include PaymentStatus
+ Include ShippingStatus
+ placedAt: `2015-09-10T14:55:50Z` (optional, string) - Timestamp of when order was placed.
+ total (required, number) - grand total value.

### FullOrder
+ id: 1 (required, number) - Unique identifier.
+ referenceNumber: `ABC-123` (required, string) - Order reference number.
+ Include OrderStatus
+ Include ShippingStatus
+ Include PaymentStatus
+ lineItems (required, LineItems) - Line items with different types.
+ adjustments (required, array[Adjustment]) - Order adjustments.
+ fraudScore: 0 (required, number) - Fraud score.
+ customer (optional, CustomerResponse) - Associated customer.
+ totals (required, Totals) - Order totals.
+ shippingMethod (optional, ShippingMethod) - Shipping method.
+ shippingAddress (optional, OrderShippingAddress) - Shipping address.
+ assignees (required, array[OrderAssignee]) - Order assignees.
+ remorsePeriodEnd: `2015-09-10T14:55:50Z` (optional, string) - Remorse period end.
+ paymentMethods (optional, array[DisplayPayment]) - Order payment.
+ lockedBy (optional, StoreAdminResponse) - Currently locked by.
+ warnings: `List of validation errors and warnings` (optional, array[string]) - Warnings.

### OrderAssignee
+ assignee (required, StoreAdminResponse) - Assigned store admin.
+ assignedAt `2015-09-10T14:55:50Z` (optional, string) - Assignment date.

### OrderShippingAddress
+ id: 1 (required, number) - Unique ID.
+ region (required, Region) - Associated region.
+ name: `Home` (required, string) - Address record name.
+ address1: `38 Baker Street` (required, string) - Actual address.
+ address2: `39 Baker Street` (optional, string) - Additional address line.
+ city: `Donkeyville` (required, string) - City.
+ zip: `55555` (required, string) - Zip code.
+ isDefault: false (required, boolean) - Defines whether shipping address is default.

### ShippingMethod
+ id: 1 (required, number) - Unique ID.
+ name: `UPS Ground` (optional, string) - Display name in Admin panel.
+ price: 10 (required, number) - Price of shipping.
+ isEnabled: true (required, boolean) - Defines whether shipping method is enabled in store.

### DisplayPayment
+ type (required, enum[string]) - Payment method type.
    + Members
        + `CreditCard`
        + `GiftCard`
        + `StoreCredit`

### Totals
+ subTotal: 100 (required, number) - Subtotal.
+ taxes: 50 (required, number) - Taxes total.
+ shipping: 5 (required, number) - Taxes total.
+ adjustments: 50 (required, number) - Adjustments total.
+ total: 100 (required, number) - Total.

### LineItems
+ skus (required, array[SkuLineItem]) - SKU's as line items.
+ giftCard (required, array[GiftCard]) - Gift cards as line items.

### SkuLineItem
+ imagePath: `http://lorempixel.com/75/75/fashion` (required, string) - Image URL.
+ name: `donkey product` (required, string) - Product name.
+ sku: `SKU-YAX` (required, string) - SKU.
+ price: 33 (required, number) - SKU price.
+ quantity: 1 (required, number) - Quantity.
+ Include LineItemStatus
+ totalPrice: 33 (required, number) - Price per item multiplied by quantity

### Adjustment
+ id: 1 (required, number) - Unique identifier.
+ amount: 10 (required, number) - Amount.
+ sourceId: 1 (required, number) - Adjustment source ID.
+ sourceType: `order` (required, string) - Adjustment source type.
+ reason: `Lorem ipsum` (required, string) - Adjustment reason.

### CreateCartPayload
+ customerId: 1 (optional, number) - Customer ID.
+ email: `john@smith.com` (optional, string) - Customer e-mail.

### UpdateLineItemsPayload
+ sku: `SKU-YAX` (required, string) - SKU.
+ quantity: 5 (required, number) - Quantity.

### UpdateShippingMethodPayload
+ shippingMethodId: 1 (required, number) - Shipping method ID.

### CreditCardPaymentPayload
+ creditCardId: 1 (required, number) - Credit Card ID

### GiftCardPaymentPayload
+ code: `ABC-123` (required, string) - Gift card code.
+ amount: 10 (required, number) - Amount to pay.

### StoreCreditPaymentPayload
+ amount: 10 (required, number) - Amount to pay.

### OrderBulkStatusUpdatePayload
+ referenceNumbers: `ABC-123` (required, array[string]) - Order reference numbers.
- Include OrderStatus
+ reasonId: 1 (optional, number) - Cancellation reason.

### OrderAssignPayload
+ assignees (required, array[number]) - StoreAdmin IDs.

### OrderBulkAssignPayload
+ referenceNumbers: `ABC-123` (required, array[string]) - Order reference numbers.
+ assigneeId: 1 (required, number) - StoreAdmin ID.

### OrderList
+ result (required, array[ListOrder]) - The resulting list of ListOrder-s.
+ Include ResultMetadata
