# Data Structures

### SavedForLater
+ id: 1 (required, number) - ID
+ name: Flonkey (optional, string) - Item name
+ sku: `SKU-YAX` (required, string) -  Item SKU
+ price: 33 (required, number) - Item price
+ createdAt: `2015-10-28T12:20:27.794Z` (required, string) - Creation date
+ imageUrl: `http://site.com/pic.jpg` (required, string) - Item picture URL
+ favorite: false (required, boolean) - Favorite?

### SaveForLaterResponse
+ result (required, array[SavedForLater]) - Save for later
+ errors (optional, array) - List of possible errors
