# Data Structures

### StoreCreditOriginType
+ originType: CsrAppeasement (required, enum[string]) - GC origin type.
    + Members
        + `csrAppeasement`
        + `giftCardTransfer`
        + `returnProcess`

### StoreCreditStatus
+ status: OnHold (required, enum[string]) - GC status.
    + Members
        + `onHold`
        + `active`
        + `canceled`

### StoreCredit
+ id: 1 (required, number) - Unique identifier.
+ createdAt: `2015-09-10T14:55:50Z` (required, string) - Creation date.
+ currency: USD (required, string) - SC currency.
+ Include StoreCreditOriginType
+ subTypeId: 1 (optional, number) - Optional subtype.
+ Include StoreCreditStatus
+ originalBalance: 50 (required, number) - Opening balance for SC (amount it was issued for).
+ currentBalance: 50 (required, number) - Opening balance minus "captured" debits.
+ availableBalance: 50 (required, number) - Opening balance minus "auth" debits.
+ canceledReason: Lorem ipsum (string) - Cancellation reason (present if SC canceled).

### StoreCreditOriginTypeResponse
+ Include StoreCreditOriginType
+ subtypes (required, array[StoreCreditSubtype]) - List of related subtypes.

### StoreCreditSubtype
+ id: 1 (required, number) - Unique ID.
+ title: `Appeasement Type A` (required, string) - Subtype title.
+ Include StoreCreditOriginType

### StoreCreditAdjustment
+ id: 1 (required, number) - Unique identifier.
+ debit: 50 (required, number) - Debit of adjustment.
+ state: Auth (required, enum[string]) - Gift Card status.
    + Members
        + `auth`
        + `capture`
        + `canceled`
+ orderRef: `ABC-123` (string) - Order reference number.

### StoreCreditBulkResponse
+ success: true (required, boolean) - Operation result.
+ id: 1 (required, number) - Requested StoreCredit identifier.
+ errors (optional, array[string]) - List of possible errors.
+ storeCredit (optional, StoreCredit) - Updated StoreCredit.

### StoreCreditCreatePayload
+ amount: 10 (required, number) - Store credit amount.
+ quantity: 1 (required, number) - Quantity.
+ reasonId: 1 (required, number) - Reason of creation.
+ subReasonId: 1 (optional, number) - Subreason.
+ currency: USD (optional, string) - Store credit currency.

### StoreCreditBulkStatusUpdatePayload
+ ids (required, array[number]) - List of Store Credit ID's.
+ status: onHold (required, string) - Status to be switched to.
+ reasonId: 1 (optional, number) - ID of cancellation reason.

### StoreCreditUpdateStatusPayload
+ status: onHold (required, string) - New store credit status.
+ reasonId: 1 (optional, number) - ID of cancellation reason.

### StoreCredits
+ result     (required, array[StoreCredit]) - The resulting list of Rma-s.
+ Include ResultMetadata

### StoreCreditAdjustments
+ result     (required, array[StoreCreditAdjustment]) - The resulting list of StoreCreditAdjustment-s.
+ Include ResultMetadata

### StoreCreditTotals
+ currentBalance: 50 (required, number) - Total current balance for customer.
+ availableBalance: 50 (required, number) - Total available balance for customer.
