# Data Structures

### StoreAdmin
+ id: 1 (required, number) - ID.
+ email: admin@admin.com (required, string) - Email.
+ name: Frankly Admin (required, string) - Name.
+ department: Superadmins (string) - Department.

### StoreAdminCreatePayload
+ email: admin@admin.com (required, string) - Email.
+ name: Frankly Admin (required, string) - Name.
+ password: somepassword (string) - Password.
+ department: Superadmins (string) - Department.

### StoreAdminUpdatePayload
+ email: admin@admin.com (required, string) - Email.
+ name: Frankly Admin (required, string) - Name.
+ department: Super Admins (string) - Department.
