# Data Structures

### CreateNotificationPayload
+ sourceDimension: `order` (required, string) - Dimension that was source for activity creation
+ sourceObjectId: `1` (required, string) - Object id that was source for activity creation
+ activityId: 1 (required, number) - Activity id to notify about
+ data: `{ "foo": "bar" }` (optional, string) - JSON data
