# Data Structures

### Image
+ src: `http://lorempixel.com/test.png` (required, string) - URL pointing to the image.
+ title: `test image` (optional, string) - Title that identifies the image.
+ alt: `some image text` (optional, string) - Alt text for the image.

### Album
+ id: 1 (required, number) - Unique identifier.
+ name: `Desktop images` (required, string) - Name of the album.
+ images (optional, array[Image]) - Images that are part of the album.
+ archivedAt: `2020-01-01T12:00:00Z` (string) - Archiving date.

### CreateAlbumPayload
+ name: `Desktop images` (required, string) - Name of the album.
+ images (optional, array[Image]) - Images that are part of the album.
