# Data Structures

### AdminNote
+ id: 1 (required, number) - Unique identifier.
+ body: `Lorem ipsum` (required, string) - Note message.
+ author (required, NoteAuthor) - Note author.
+ createdAt: `2020-01-01T12:00:00Z` (required, string) - Creation date.

### NoteAuthor
+ name: `John Smith` (required, string) - Author name.
+ email: `john@smith.com` (required, string) - E-mail.

### AdminNotes (array[AdminNote])
