/* @flow */

import { range, invert, rangeRight } from 'lodash';
import {
  get,
  add,
  flow,
  getOr,
  indexOf,
  subtract,
  toString,
  placeholder as _,
} from 'lodash/fp';

import type { FormField } from '../../core/types/fields';

const LIST_DAYS = range(1, 32);
const LIST_YEARS = rangeRight(1950, new Date().getFullYear() + 1);
const LIST_MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

const LIST_STATES = {
  Alabama: 'AL',
  Alaska: 'AK',
  'American Samoa': 'AS',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District Of Columbia': 'DC',
  'Federated States Of Micronesia': 'FM',
  Florida: 'FL',
  Georgia: 'GA',
  Guam: 'GU',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  'Marshall Islands': 'MH',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Northern Mariana Islands': 'MP',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Palau: 'PW',
  Pennsylvania: 'PA',
  'Puerto Rico': 'PR',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  'Virgin Islands': 'VI',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

export const fields: Array<FormField> = [
  {
    name: 'legal_entity_name',
    type: 'text',
    placeholder: 'Business: Name',
    validation: 'required',
  },
  {
    name: 'bank_account_number',
    type: 'text',
    placeholder: 'Bank Account Number',
    validation: 'required',
  },
  {
    name: 'bank_routing_number',
    type: 'text',
    placeholder: 'Bank Routing Number',
    validation: 'required format.routing_number',
  },
  {
    name: 'representative_ssn_trailing_four',
    type: 'text',
    placeholder: 'Business Rep: Last Four of SSN',
    validation: 'required format.SSN_last_four',
  },
  {
    name: 'legal_entity_tax_id',
    type: 'text',
    placeholder: 'Legal Entity Tax ID',
  },
  {
    name: 'business_founded_day',
    type: 'select',
    multi: false,
    placeholder: 'Business Rep DOB: Day',
    values: LIST_DAYS,
    parse: toString,
    validation: 'required',
  },
  {
    name: 'business_founded_month',
    type: 'select',
    multi: false,
    placeholder: 'Business Rep DOB: Month',
    values: LIST_MONTHS,
    normalize: flow(indexOf(_, LIST_MONTHS), add(1), toString),
    format: flow(subtract(_, 1), get(_, LIST_MONTHS)),
    validation: 'required',
  },
  {
    name: 'business_founded_year',
    type: 'select',
    multi: false,
    placeholder: 'Business Rep DOB: Year',
    values: LIST_YEARS,
    parse: toString,
    validation: 'required',
  },
  {
    name: 'address1',
    type: 'text',
    placeholder: 'Business Address 1',
    validation: 'required',
  },
  {
    name: 'address2',
    type: 'text',
    placeholder: 'Business Address 2',
  },
  {
    name: 'city',
    type: 'text',
    placeholder: 'City',
    validation: 'required',
  },
  {
    name: 'state',
    type: 'select',
    multi: false,
    placeholder: 'State',
    values: Object.keys(LIST_STATES),
    format: get(_, invert(LIST_STATES)),
    normalize: getOr(null, _, LIST_STATES),
    validation: 'required',
  },
  {
    name: 'zip',
    type: 'text',
    placeholder: 'ZIP Code',
    validation: 'required format.zip',
  },
];
