#!/usr/bin/env bash
set -e

ROOT_DIR="$(git rev-parse --show-toplevel)"
SCALAFMT_DIR="${ROOT_DIR}/utils/scalafmt"
source "${SCALAFMT_DIR}"/shared-functions.sh

SCALA_FILES_IN_LAST_COMMIT=$(scala_files_in_last_commit)

if [ "${SCALA_FILES_IN_LAST_COMMIT}" ]; then
  ${SCALAFMT_DIR}/scalafmt.sh --test ${SCALA_FILES_IN_LAST_COMMIT} &> /dev/null || NEED_FMT=1
  if [ ${NEED_FMT} ]; then
    echo "******************************************************************"
    echo "     Some Scala files are not formatted properly! Please run"
    echo "          utils/scalafmt/scalafmt-last-commit.sh"
    echo "     to format sources changed in last commit!"
    echo "******************************************************************"
  else true; fi
else true; fi
