# Open to All

Public endpoints which do not require authentication.

<!-- include(objects/common.apib) -->
<!-- include(objects/customers.apib) -->

## Group Auth

Authorization-related endpoints.

<!-- include(resources/public_auth.apib) -->
