'use strict';

const GiftCardConstants = {
  UPDATE_GIFT_CARDS: 'UPDATE_GIFT_CARDS',
  FETCH_GIFT_CARDS: 'FETCH_GIFT_CARDS',
  FETCH_GIFT_CARD: 'FETCH_GIFT_CARD',
  GIFT_CARD_FAILED: 'GIFT_CARD_FAILED',
  CREATE_GIFT_CARD: 'CREATE_GIFT_CARD',
  EDIT_GIFT_CARD: 'EDIT_GIFT_CARD'
};

export default GiftCardConstants;
