const LineItemsConstants = {
  ORDER_LINE_ITEM_SUCCESS: 'ORDER_LINE_ITEM_SUCCESS',
  RETURN_LINE_ITEM_SUCCESS: 'RETURN_LINE_ITEM_SUCCESS',
  FAILED_LINE_ITEMS: 'FAILED_LINE_ITEMS'
};

export default LineItemsConstants;
