## Orders [/v1/my/orders]

Customer's orders.

### View [GET /v1/my/orders/{refNum}]

+ Parameters
    + refNum: `BR1001` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)
