# Data Structures

### ExportEntityByIds
+ description: `whatever` (optional, string) - Description of an export.
+ fields: `id` (required, array[string]) - List of fields to export.
+ ids (required, array[number]) - List of ids.

### ExportEntityByQuery
+ description: `whatever` (optional, string) - Description of an export.
+ fields: `id` (required, array[string]) - List of fields to export.
+ query (required, RawQuerySample) - Search query.

### RawQuerySample
+ bool (object)

