# Data Structures

## SkuPayload
+ attributes: `<json>` (required, string) - SKU attributes.

## SkuResponse
+ id: 1 (required, number) - SKU ID.
+ attributes: `<json>` (required, string) - SKU attributes.
+ context (required, ObjectContext) - Related context.
+ albums (required, array[Album]) - SKU albums.
+ archivedAt: `2020-01-01T12:00:00Z` (optional, string) - Archiving date.
