# Data Structures

## Watcher
+ id: 1 (required, number) - Watcher ID.
+ assignee (required, object) - Watcher details.
+ assignmentType: `watcher` (required, string) - Assignment type.

## AddWatchersPayload
+ assignees (required, array[number]) - Watchers to add.
