FROM golang

RUN curl https://glide.sh/get | sh

ADD . /go/src/github.com/FoxComm/highlander/middlewarehouse
RUN cd /go/src/github.com/FoxComm/highlander/middlewarehouse && glide install
RUN go install github.com/FoxComm/highlander/middlewarehouse/consumers/gift-cards

ENTRYPOINT /go/bin/gift-cards
