river_rock_proxy.pdf: river_rock_proxy.tex
	pdflatex --shell-escape river_rock_proxy.tex
	pdflatex --shell-escape river_rock_proxy.tex

intelligent_commerce.pdf: intelligent_commerce.tex
	pdflatex --shell-escape intelligent_commerce.tex
	pdflatex --shell-escape intelligent_commerce.tex

all: river_rock_proxy.pdf intelligent_commerce.pdf

.PHONY: river_rock_proxy.pdf intelligent_commerce.pdf
