bandit_proxy.pdf: bandit_proxy.tex
	pdflatex --shell-escape bandit_proxy.tex
	pdflatex --shell-escape bandit_proxy.tex

intelligent_commerce.pdf: intelligent_commerce.tex
	pdflatex --shell-escape intelligent_commerce.tex
	pdflatex --shell-escape intelligent_commerce.tex

all: bandit_proxy.pdf intelligent_commerce.pdf

.PHONY: bandit_proxy.pdf intelligent_commerce.pdf
