## Orders [/v1/orders/{refNum}]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.

### List [GET /v1/orders{?size,from,sortBy}]

Lists basic information of Orders for a quick table view to drill-down into
orders further.

+ Parameters
    + size:   1           (optional, number)       - Page size.
    + from:   1           (optional, number)       - Start element (counting from 0) or # of elements to skip.
    + sortBy: `id`        (optional, enum[string]) - Field to sort by (`-fieldName` for descending order).
        + Members
            + `id`
            + `referenceNumber`
            + `customerId`
            + `status`
            + `isLocked`
            + `placedAt`
            + `remorsePeriodEnd`
            + `customer_isDisabled`
            + `customer_disabledBy`
            + `customer_isBlacklisted`
            + `customer_blacklistedBy`
            + `customer_blacklistedReason`
            + `customer_email`
            + `customer_name`
            + `customer_phoneNumber`
            + `customer_location`
            + `customer_modality`
            + `customer_isGuest`
            + `customer_createdAt`
+ Response 200 (application/json)
  + Attributes (OrderList)

### View [GET]

+ Response 200 (application/json)
  + Attributes (FullOrder)

### Create [POST /v1/orders]

Creates a cart for an existing customer (or guest account) when `customerId`
given or creates a cart along with a new guest account when `email` is given.

+ Request (application/json)
    + Attributes (CreateCartPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Bulk Update Status [PATCH /v1/orders]

+ Request (application/json)
    + Attributes (OrderBulkStatusUpdatePayload)
+ Response 200 (application/json)
    + Attributes (OrderList)

### Lock [POST /v1/orders/{refNum}/lock]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Unlock [POST /v1/orders/{refNum}/unlock]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)    

### Increase Remorse Period [POST /v1/orders/{refNum}/increase-remorse-period]

Order must be in `remorseHold` status.

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Update SKU Line Items [POST /v1/orders/{refNum}/line-items]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
+ Request (application/json)
    + Attributes (array[UpdateLineItemsPayload])
+ Response 200 (application/json)
    + Attributes (FullOrder)

## Gift Card Line Items [/v1/orders/{refNum}/gift-cards/{code}]

### Add [POST /v1/orders/{refNum}/gift-cards]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
+ Request (application/json)
    + Attributes (GiftCardSingleCreatePayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Edit [PATCH]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
    + code: `ABC-123` (required, string) - Gift Card code.
+ Request (application/json)
    + Attributes (GiftCardSingleCreatePayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order referenceNumber.
    + code: `ABC-123` (required, string) - Gift Card code.
+ Response 200 (application/json)
    + Attributes (FullOrder)

## Credit Card Payments [/v1/orders/{refNum}/payment-methods/credit-cards]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

+ Request (application/json)
    + Attributes (CreditCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Edit [PATCH]

+ Request (application/json)
    + Attributes (CreditCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)    

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (FullOrder)

## Gift Card Payments [/v1/orders/{refNum}/payment-methods/gift-cards]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

+ Request (application/json)
    + Attributes (GiftCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Edit [PATCH]

+ Request (application/json)
    + Attributes (GiftCardPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (FullOrder)

## Store Credit Payments [/v1/orders/{refNum}/payment-methods/store-credits]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

+ Request (application/json)
    + Attributes (StoreCreditPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Edit [PATCH]

+ Request (application/json)
    + Attributes (StoreCreditPaymentPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (FullOrder)    

## Shipping Method [/v1/orders/{refNum}/shipping-methods]

Shipping methods are used to describe the ways that the contents of a cart can
transported to the customer. All actions that occur against this set of
endpoints modify which shipping method is used by the cart.

### Update [PATCH]

Changes the shipping method to a cart.

+ Parameters
    + refNum: 1 (required, string) - Order referenceNumber
+ Request (application/json)
    + Attributes (UpdateShippingMethodPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

Removes the shipping method from the cart.

+ Parameters
    + refNum: 1 (required, string) - Order reference number
+ Response 204

## Shipping Address [/v1/orders/{refNum}/shipping-address]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Add [POST]

+ Request (application/json)
    + Attributes (CreateAddressPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Add By Address ID [PATCH /v1/orders/{refNum}/shipping-address/{addressId}]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number.
    + addressId: 1 (required, number) - Address ID.
+ Response 200 (application/json)
    + Attributes (FullOrder)    

### Update [PATCH]

+ Request (application/json)
    + Attributes (UpdateAddressPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (FullOrder)

## Assignees [/v1/orders/{refNum}/assignees]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Assign [POST]

+ Request (application/json)
    + Attributes (OrderAssignPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Bulk Assign [POST /v1/orders/assignees]

+ Request (application/json)
    + Attributes (OrderBulkAssignPayload)
+ Response 200 (application/json)
    + Attributes (OrderList)

### Bulk Unassign [POST /v1/orders/assignees/delete]

+ Request (application/json)
    + Attributes (OrderBulkAssignPayload)
+ Response 200 (application/json)
    + Attributes (OrderList)

## Watchers [/v1/orders/{refNum}/watchers]

+ Parameters
    + refNum: `ABC-123` (required, string) - Order reference number

### Assign [POST]

+ Request (application/json)
    + Attributes (OrderWatchPayload)
+ Response 200 (application/json)
    + Attributes (FullOrder)

### Bulk Watch [POST /v1/orders/watchers]

+ Request (application/json)
    + Attributes (OrderBulkAssignPayload)
+ Response 200 (application/json)
    + Attributes (OrderList)

### Bulk Unwatch [POST /v1/orders/watchers/delete]

+ Request (application/json)
    + Attributes (OrderBulkWatchPayload)
+ Response 200 (application/json)
    + Attributes (OrderList)    