## Return [/v1/rmas/{refNum}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### List [GET /v1/rmas{?size,from,sortBy}]

+ Parameters
    + size:   1           (optional, number)       - Page size.
    + from:   1           (optional, number)       - Start element (counting from 0) or # of elements to skip.
    + sortBy: `id`        (optional, enum[string]) - Field to sort by (`-fieldName` for descending order).
        + Members
            + `id`
            + `referenceNumber`
            + `orderId`
            + `orderRefNum`
            + `rmaType`
            + `status`
            + `locked`
            + `customerId`
            + `storeAdminId`
+ Response 200 (application/json)
    + Attributes (Rmas)

### List by Customer [GET /v1/rmas/customer/{customerId}{?size,from,sortBy}]

+ Parameters
    + customerId: 1 (required, number) - Customer ID.
    + size:   1           (optional, number)       - Page size.
    + from:   1           (optional, number)       - Start element (counting from 0) or # of elements to skip.
    + sortBy: `id`        (optional, enum[string]) - Field to sort by (`-fieldName` for descending order).
        + Members
            + `id`
            + `referenceNumber`
            + `orderId`
            + `orderRefNum`
            + `rmaType`
            + `status`
            + `locked`
            + `customerId`
            + `storeAdminId`
+ Response 200 (application/json)
    + Attributes (Rmas)

### List by Order [GET /v1/rmas/order/{orderRef}{?size,from,sortBy}]

+ Parameters
    + orderRef: `ABC-123` (required, string) - Order reference number.
    + size:   1           (optional, number)       - Page size.
    + from:   1           (optional, number)       - Start element (counting from 0) or # of elements to skip.
    + sortBy: `id`        (optional, enum[string]) - Field to sort by (`-fieldName` for descending order).
        + Members
            + `id`
            + `referenceNumber`
            + `orderId`
            + `orderRefNum`
            + `rmaType`
            + `status`
            + `locked`
            + `customerId`
            + `storeAdminId`
+ Response 200 (application/json)
    + Attributes (Rmas)

### View [GET]

+ Response 200 (application/json)
    + Attributes (Rma)
    
### Edit View [GET /v1/rmas/{refNum}/expanded]

Expanded view with embedded Order + warnings and includes.

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
+ Response 200 (application/json)
    + Attributes (RmaExpanded)

### View Lock [GET /v1/rmas/{refNum}/lock]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
+ Response 200 (application/json)
    + Attributes (RmaLockInfo)

### Lock [POST /v1/rmas/{refNum}/lock]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
+ Response 200 (application/json)
    + Attributes (Rma)

### Unlock [POST /v1/rmas/{refNum}/unlock]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
+ Response 200 (application/json)
    + Attributes (Rma)

### Create [POST /v1/rmas]

+ Request (application/json)
    + Attributes (RmaCreatePayload)
+ Response 200 (application/json)
    + Attributes (Rma)

### Update Status [PATCH /v1/rmas/{refNum}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
+ Request (application/json)
    + Attributes (RmaStatusUpdatePayload)
+ Response 200 (application/json)
    + Attributes (Rma)

### Update Message To Customer [POST /v1/rmas/{refNum}/message]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
+ Request (application/json)
    + Attributes (RmaMessageToCustomerUpdatePayload)
+ Response 200 (application/json)
    + Attributes (Rma)

## Line Items SKUs [/v1/rmas/{refNum}/line-items/skus]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### Add [POST]

+ Request (application/json)
    + Attributes (array[RmaSkuLineItemPayload])
+ Response 200 (application/json)
    + Attributes (Rma) 

### Delete [DELETE /v1/rmas/{refNum}/line-items/skus/{id}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
    + id: 1 (required, number) - Line item ID
+ Response 200 (application/json)
    + Attributes (Rma)

## Line Items Gift Cards [/v1/rmas/{refNum}/line-items/gift-cards]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### Add [POST]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA referenceNumber.
+ Request (application/json)
    + Attributes (array[RmaGiftCardLineItemPayload])
+ Response 200 (application/json)
    + Attributes (Rma)

### Delete [DELETE /v1/rmas/{refNum}/line-items/gift-cards/{id}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
    + id: 1 (required, number) - Line item ID
+ Response 200 (application/json)
    + Attributes (Rma)

## Line Items Shipping Costs [/v1/rmas/{refNum}/line-items/shipping-costs]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### Add [POST]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA referenceNumber.
+ Request (application/json)
    + Attributes (array[RmaShippingCostLineItemPayload])
+ Response 200 (application/json)
    + Attributes (Rma)

### Delete [DELETE /v1/rmas/{refNum}/line-items/shipping-costs/{id}]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number
    + id: 1 (required, number) - Line item ID
+ Response 200 (application/json)
    + Attributes (Rma)    

## Credit Card Payments [/v1/rmas/{refNum}/payment-methods/credit-cards]

+ Parameters
    + refNum: `ABC-123` (required, string) - RMA reference number

### Add [POST]

+ Request (application/json)
    + Attributes (RmaPaymentPayload)
+ Response 200 (application/json)
    + Attributes (Rma)

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (Rma)

## Gift Card Payments [/v1/rmas/{refNum}/payment-methods/gift-cards]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### Add [POST]

+ Request (application/json)
    + Attributes (RmaPaymentPayload)
+ Response 200 (application/json)
    + Attributes (Rma)

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (Rma)

## Store Credit Payments [/v1/rmas/{refNum}/payment-methods/store-credits]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### Add [POST]

+ Request (application/json)
    + Attributes (RmaPaymentPayload)
+ Response 200 (application/json)
    + Attributes (Rma)

### Delete [DELETE]

+ Response 200 (application/json)
    + Attributes (Rma)

## Assignees [/v1/rmas/{refNum}/assignees]

+ Parameters
    + refNum: `ABC-123.1` (required, string) - RMA reference number

### Assign [POST]

+ Request (application/json)
    + Attributes (RmaAssignPayload)
+ Response 200 (application/json)
    + Attributes (Rma)

### Bulk Assign [POST /v1/rmas/assignees]

+ Request (application/json)
    + Attributes (RmaBulkAssignPayload)
+ Response 200 (application/json)
    + Attributes (Rmas)

### Bulk Unassign [POST /v1/rmas/assignees/delete]

+ Request (application/json)
    + Attributes (RmaBulkAssignPayload)
+ Response 200 (application/json)
    + Attributes (Rmas)