# Phoenix: Store Admin

All routes related to store admin (not store front).

<!-- include(objects/common.apib) -->
<!-- include(objects/customers.apib) -->
<!-- include(objects/gift_card.apib) -->
<!-- include(objects/notes.apib) -->
<!-- include(objects/order.apib) -->
<!-- include(objects/reasons.apib) -->
<!-- include(objects/rma.apib) -->
<!-- include(objects/store_credit.apib) -->
<!-- include(objects/save_for_later.apib) -->

## Group Customers

Customers represents a core type of our system.

<!-- include(admin_customers.apib) -->

## Group Reason

Reasons are widely-used descriptions of various management actions, e.g. cancellation of GiftCard.

<!-- include(admin_reasons.apib) -->

## Group Gift Card

Gift Card is a tender type created and maintained by FoxCommerce. Gift Cards are not related to any customer account.

<!-- include(admin_gift_cards.apib) -->

## Group Store Credit

StoreCredit is a tender type created and maintained by FoxCommerce. Store Credits are always tied to a customer account.

<!-- include(admin_store_credits.apib) -->

## Group Orders

Orders, oh my!

<!-- include(admin_orders.apib) -->

## Group Notes

Notes for various entities.

<!-- include(admin_notes.apib) -->

## Group Returns

Returns are frequently called RMA (return merchandise authorization).

<!-- include(admin_rmas.apib) -->

## Group Save for later

They'll buy it... Later.

<!-- include(admin_save_for_later.apib) -->
