# Phoenix: Store Admin

All endpoints related to store administration (requires store admin authentication).

<!-- include(objects/common.apib) -->
<!-- include(objects/credit_cards.apib) -->
<!-- include(objects/customers.apib) -->
<!-- include(objects/gift_card.apib) -->
<!-- include(objects/location.apib) -->
<!-- include(objects/notes.apib) -->
<!-- include(objects/order.apib) -->
<!-- include(objects/reasons.apib) -->
<!-- include(objects/rma.apib) -->
<!-- include(objects/store_credit.apib) -->
<!-- include(objects/save_for_later.apib) -->

## Group Common

Helper endpoints with meta-information (gift card types, reasons, etc.)

<!-- include(admin_common.apib) -->

## Group Customers

Customer represents an account of person who buys products in the store.

<!-- include(admin_customers.apib) -->

## Group Orders

Order mainly consists of list of line items, payment methods, shipments and calculated totals. It is always related to specific customer account.

<!-- include(admin_orders.apib) -->

## Group RMAs

RMA is abbreviation for "Return Merchandise Authorization". RMA is always related to particular Order, but one order can have multiple RMAs.

<!-- include(admin_rmas.apib) -->

## Group Gift Cards

Gift Card is a payment method with unique code, not related to any customer account.

<!-- include(admin_gift_cards.apib) -->

## Group Store Credits

Store Credit is a payment method always tied to specific customer account. One customer can have multiple store credits.

<!-- include(admin_store_credits.apib) -->

## Group Save For Later

Save For Later concept is similar to wishlists - a list of products that customer wants to save for future purchases.

<!-- include(admin_save_for_later.apib) -->

## Group Notes

Notes represent additional text data added by store admins to orders, RMAs and gift cards, viewable by other store admins.

<!-- include(admin_notes.apib) -->