## List [GET /v1/my/payment-methods/store-credits]

+ Response 200 (application/json)
    + Attributes (StoreCredits)

## View [GET /v1/my/payment-methods/store-credits/{id}]

+ Parameters
	+ id: 1 (required, number) - Store Credit ID
+ Response 200 (application/json)
    + Attributes (StoreCredit)