## View Cart [GET /v1/my/cart]

+ Response 200 (application/json)
    + Attributes (FullOrder)

## View Order [GET /v1/my/order]

Alias of View Cart.

+ Response 200 (application/json)
    + Attributes (FullOrder)

## Checkout [POST /v1/my/order/checkout]

Place order using current customer's cart.

+ Response 200 (application/json)
    + Attributes (FullOrder)
