# Phoenix: Customer

Customer related endpoints (requires customer authentication).

<!-- include(objects/common.apib) -->
<!-- include(objects/location.apib) -->
<!-- include(objects/customers.apib) -->
<!-- include(objects/order.apib) -->
<!-- include(objects/gift_card.apib) -->
<!-- include(objects/rma.apib) -->
<!-- include(objects/store_credit.apib) -->

## Group Cart

Cart management endpoints.

<!-- include(customer_cart.apib) -->

## Group Addresses

Address management endpoints.

<!-- include(customer_addresses.apib) -->

## Group Store Credits

Store credit management endpoints.

<!-- include(customer_store_credits.apib) -->