# Phoenix: Public

Public routes which do not require authentication.

<!-- include(objects/common.apib) -->
<!-- include(objects/location.apib) -->

## Group Country

Countries and regions.

<!-- include(public_countries.apib) -->