## List Regions [GET /v1/regions]

+ Response 200 (application/json)
    + Attributes (Regions)

### List Countries [GET /v1/countries]

+ Response 200 (application/json)
    + Attributes (Countries)

### View Country [GET /v1/countries/{countryId}]

+ Parameters
	+ countryId: 1 (required, number) - Country ID
+ Response 200 (application/json)
    + Attributes (FullCountry)