# Phoenix: Public

Public endpoints which do not require authentication.

<!-- include(objects/common.apib) -->
<!-- include(objects/location.apib) -->
<!-- include(objects/customers.apib) -->
<!-- include(objects/notes.apib) -->

## Group Customer

Registration-related endpoints.

<!-- include(public_customer.apib) -->

## Group Location

Helper endpoints which returns available countries and regions.

<!-- include(public_countries.apib) -->

## Group SKU

Helper endpoints which returns available SKUs.

<!-- include(public_skus.apib) -->