## Taxonomies [/v1/taxonomies/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxonomy is viewable.
    + id: `1` (required, number) - Unique identifier for a Taxonomy.

### View [GET]

+ Response 200 (application/json)
  + Attributes (TaxonomyResponse)

### Create [POST /v1/taxonomies/{context}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxonomy is viewable.
+ Request (application/json)
    + Attributes (CreateTaxonomyPayload)
+ Response 200 (application/json)
  + Attributes (TaxonomyResponse)

### Update [PATCH /v1/taxonomies/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxonomy is viewable.
    + id: `1` (required, number) - Unique identifier for a Taxonomy.
+ Request (application/json)
    + Attributes (UpdateTaxonomyPayload)
+ Response 200 (application/json)
  + Attributes (TaxonomyResponse)

### Delete [DELETE /v1/taxonomies/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxonomy is viewable.
    + id: `1` (required, number) - Unique identifier for a Taxonomy.
+ Response 200 (application/json)

## Taxons [/v1/taxons/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxon is viewable.
    + id: `1` (required, number) - Unique identifier for a Taxon.

### View [GET]

+ Response 200 (application/json)
  + Attributes (TaxonResponse)

### Create [POST /v1/taxonomy/{context}/{taxonomy_id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxon is viewable.
    + taxonomy_id: `1` (required, number) - Unique identifier for a Taxonomy.
+ Request (application/json)
    + Attributes (CreateTaxonPayload)
+ Response 200 (application/json)
  + Attributes (TaxonResponse)

### Update [PATCH /v1/taxons/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxon is viewable.
    + id: `1` (required, number) - Unique identifier for a Taxon.
+ Request (application/json)
    + Attributes (UpdateTaxonPayload)
+ Response 200 (application/json)
  + Attributes (TaxonResponse)

### Delete [DELETE /v1/taxons/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a taxonomy is viewable.
    + id: `1` (required, number) - Unique identifier for a Taxon.
+ Response 200 (application/json)
