## Stock Locations [/v1/inventory/stock-locations/{id}]

Stock Locations are representations of any place that inventory may be stored.
FoxCommerce Inventory is designed to be manage and track inventory over
multiple stock locations for a given storefront, as well as over multiple types
of stock location.

_Stock Location Types_

- **Warehouse** (currently supported)
- **Retail Store** (coming soon)
- **Pop-up Shop** (coming soon)

+ Parameters
    + id: 1 (required, number) - Stock Location ID.

### View [GET]

+ Response 200 (application/json)
    + Attributes (StockLocationResponse)

### Create [POST /v1/inventory/stock-locations]

+ Request (application/json)
    + Attributes (StockLocationPayload)
+ Response 201 (application/json)
    + Attributes (StockLocationResponse)

### Update [PUT]

+ Request (application/json)
    + Attributes (StockLocationPayload)
+ Response 200 (application/json)
    + Attributes (StockLocationResponse)

### Delete [DELETE]

+ Response 204
