## Coupons [/v1/coupons/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which the coupon is viewable.
    + id: `1` (required, number) - Coupon ID.

### Create [POST /v1/coupons/{context}]

+ Parameters
    + context: `default` (required, string) - The context in which the coupon will be viewable.
+ Request (application/json)
    + Attributes (CouponPayload)
+ Response 200 (application/json)
    + Attributes (Coupon)

### View [GET]

+ Response 200 (application/json)
    + Attributes (Coupon)

### View By Code [GET /v1/coupons/{context}/{code}/baked]

+ Parameters
    + context: `default` (required, string) - The context in which the coupon is viewable.
    + code: `ABC-123` (required, string) - Related coupon code.
+ Response 200 (application/json)
    + Attributes (Coupon)

### Archive [DELETE]

+ Response 200 (application/json)
    + Attributes (Coupon)

### Get Coupon Codes [GET /v1/coupons/codes/{id}]

+ Parameters
    + id: `1` (required, number) - Related coupon ID.
+ Response 200 (application/json)
    + Attributes (array[CouponCode])
