## Account [/v1/my/account]

### View [GET]

+ Response 200 (application/json)
    + Attributes (CustomerResponse)

### Update [PATCH]

+ Request (application/json)
	+ Attributes (CustomerUpdatePayload)
+ Response 200 (application/json)
    + Attributes (CustomerResponse)
