### Login [POST /v1/public/login]

+ Request (application/json)
   + Attributes (LoginPayload)
+ Response 200 (application/json)
   + Attributes (LoginResponse)

### Logout [POST /v1/public/logout]

+ Request (application/json)
+ Response 200 (application/json)

### Registration [POST /v1/public/registrations/new]

+ Request (application/json)
   + Attributes (CustomerCreatePayload)
+ Response 200 (application/json)
    + Attributes (CustomerResponse)

### List of (US) regions [GET /v1/public/regions]

+ Include BaseCountry
+ Response 200 (application/json)
    + Attributes (array[Region])


### Get (US) region by a short name [GET /v1/public/regions/{regionShortName}]

+ Include BaseCountry
+ Attribute
   + regionShortName:`default` (required, string) - Region short name (2-letters)
+ Response 200 (application/json)
    + Attributes (Region)
