FORMAT: 1A
HOST: https://developer.foxcommerce.com

# API Reference

!!! summary

:::main
The FoxCommerce API is organized around [REST](
http://en.wikipedia.org/wiki/Representational_State_Transfer)
and is organized around predictable, resource-oriented URLs. All API endpoints
are stateless, respond with JSON, and indicate errors using HTTP status codes
with standard error messages.
:::

!!!

!!! summary
## Authentication
!!!

!!! summary
  ::: main
  Authenticate your account using your organization, username, and password to
  create a [JSON Web Token](https://jwt.io) (JWT) that can be passed to the API
  as a header or cookie.
  :::

  ::: example
  ### Test
  Let's give you some warning information
  :::
!!!

!!! summary
::: main
## Error Handling

Let's handle some errors
:::
!!!
