# Data Structures

## ProductPayload
+ attributes: `<json>` (required, string) - Product attributes.
+ skus (required, array[SkuPayload]) - Associated SKUs.

## ProductResponse
+ id: 1 (required, number) - Product ID.
+ slug (required, string) - Product slug.
+ attributes: `<json>` (required, string) - Product attributes.
+ context (required, ObjectContext) - Related context.
+ albums (required, array[AlbumResponse]) - Product albums.
+ archivedAt: `2020-01-01T12:00:00Z` (optional, string) - Archiving date.
+ skus (required, array[SkuResponse]) - Associated SKUs.
+ variants (required, array[string]) - Associated variants.
+ taxons (required, array[TaxonResponse]) - Associated taxons.
