# Data Structures

### ReturnHeader
+ id: 1 (required, number) - Unique identifier.
+ referenceNumber: `RMA-123` (required, string) - Return reference number.

### ReturnType
+ returnType: `standard` (required, enum[string]) - Return type.
    + Members
        + `standard`
        + `creditOnly`
        + `restockOnly`

### ReturnState
+ state: `pending` (required, enum[string]) - State to be switched to.
    + Members
        + `pending`
        + `processing`
        + `review`
        + `complete`
        + `canceled`

### ReturnLineItems
+ lineItems
    + skus (required, array[ReturnSkuLineItem]) - Returned line items.
    + shippingCosts (optional, ReturnShippingCostLineItem) - Returned shipping cost.

### ReturnLineItem
+ id: 1 (required, number) - Return line item unique identifier.
+ reason: `Too hipsterish` (required, string) - Return reason.
+ price: 100 (required, number) - Price of returned line item.
+ currency: `USD` (required, string) - Currency of the returned line item.

### ReturnSkuLineItem
+ Include ReturnLineItem
+ imagePath: `http://testsku.png` (required, string) - URL to an image of the returned SKU.
+ title: `Big sunglasses, not Emperor sunglassess` (required, string) - SKU title.
+ sku: `SKU-SBG` (required, string) - SKU code.
+ quantity 1 (required, string) - Returned sku quantity.

### ReturnShippingCostLineItem
+ Include ReturnLineItem
+ name: `Standard` (required, string) - Name of the shipping method.
+ amount: `30` (required, number) - Returned amount of the shipping method.

### ReturnPayments
+ payments
    + creditCard (optional, ReturnCreditCardPayment) - Refund via credit card.
    + giftCard (optional, ReturnGiftCardPayment) - Refund via gift card.
    + storeCredit (optional, ReturnStoreCreditPayment) - Refund via store credit.

### ReturnPayment
+ id: 1 (required, number) - Payment unique identifier.
+ amount: 10 (required, number) - Amount (to be) refunded to this payment method.
+ currency: `USD` (required, string) - Currency of the return payment.

### ReturnCreditCardPayment
+ Include ReturnPayment

### ReturnGiftCardPayment
+ Include ReturnPayment
+ code: `ABC-123` (required, string) - Gift card code.

### ReturnStoreCreditPayment
+ Include ReturnPayment

### ReturnTotals
+ subTotal: 70 (required, number) - Subtotal before taxes.
+ taxes: 10 (required, number) - Taxes to be subtracted.
+ shipping: 25 (required, number) - Shipping cost to be returned.
+ adjustments: 0 (required, number) - Adjustments from returned line items.
+ total: 105 (required, number) - Final total value.

### ReturnBase
+ Include ReturnType
+ Include ReturnState
+ Include ReturnLineItems
+ Include ReturnPayments
+ customer (optional, CustomerResponse) - Customer who created Return.
+ storeAdmin (optional, StoreAdminResponse) - StoreAdmin who created Return.
+ messageToCustomer: `Lorem ipsum` (optional, string) - Message to customer to be sent at the end of processing.
+ canceledReasonId: 1 (optional, number) - Possible cancellation reason ID.
+ createdAt: `2020-01-01T12:00:00Z` (required, string) - Creation date.
+ updatedAt: `2020-01-01T12:00:00Z` (required, string) - Last update date.
+ totals (required, ReturnTotals) - Total price of return.

### Return
+ Include ReturnHeader
+ orderRefNum: `ABC-123` (required, string) - Order reference number.
+ Include ReturnBase

### ReturnCreatePayload
+ orderRefNum: `ABC-123` (required, string) - Related order refNum.
+ Include ReturnType

### ReturnStateUpdatePayload
+ Include ReturnState
+ reasonId (optional, number) - Possible reason, required for cancellation, but cannot be set for any other state.

### ReturnSkuLineItemPayload
+ sku: `ABC-123` (required, string) - SKU code.
+ quantity: 1 (required, number) - Quantity.
+ reasonId: 1 (required, number) - Return reason.

### ReturnShippingCostLineItemPayload
+ amount: 10 (required, number) - Amount.
+ reasonId: 1 (required, number) - Return reason.

### ReturnPaymentsPayload
+ payments (required, object) - Return payments.
    + creditCard: 100 (optional, number) - Refund amount via credit card.
    + giftCard: 50 (optional, number) - Refund amount via gift card.
    + storeCredit: 30 (optional, number) - Refund amount via store credit.

### ReturnPaymentPayload
+ amount: 10 (required, number) - Amount.

### ReturnMessageToCustomerPayload
+ message: `Lorem ipsum` (required, string) - Desired message to customer after processing completes. Pass an empty string if you want to disable sending anything.

### ReturnReasonPayload
+ name: `Lorem ipsum` (required, string) - Reason name to be set.
