-- customers
refresh materialized view concurrently customers_ranking;
refresh materialized view concurrently customer_orders_view;
refresh materialized view concurrently customer_purchased_items_view;
refresh materialized view concurrently customer_shipping_addresses_view;
refresh materialized view concurrently customer_billing_addresses_view;
refresh materialized view concurrently customer_store_credit_view;
refresh materialized view concurrently customer_save_for_later_view;
refresh materialized view concurrently customers_search_view;

-- orders
refresh materialized view concurrently order_line_items_view;
refresh materialized view concurrently order_payments_view;
refresh materialized view concurrently order_credit_card_payments_view;
refresh materialized view concurrently order_gift_card_payments_view;
refresh materialized view concurrently order_store_credit_payments_view;
refresh materialized view concurrently order_shipments_view;
refresh materialized view concurrently order_shipping_addresses_view;
refresh materialized view concurrently order_billing_addresses_view;
refresh materialized view concurrently order_assignments_view;
refresh materialized view concurrently order_rmas_view;
refresh materialized view concurrently orders_search_view;

-- store admins
refresh materialized view concurrently store_admin_assignments_view;
refresh materialized view concurrently store_admins_search_view;
