## Group Customer Management

The Fox Platform provides a deep set of capabilities for managing, understanding,
and engaging with your customers. This section contains the resources needed to
understand and manage customer account, view their current cart, previous orders,
purchased items, and group together for easy and powerful analytics.

<!-- include(resources/admin_customers.apib) -->
<!-- include(resources/admin_customers_groups.apib) -->
