## Group Inventory Management

This section covers all the endpoints that a site administrator could use to
view and manage inventory and shipping information in FoxCommerce. Every
endpoint in this section required authentication.

<!-- include(resources/admin_stock_item_summaries.apib) -->
<!-- include(resources/admin_stock_locations.apib) -->
<!-- include(resources/admin_stock_items.apib) -->
<!-- include(resources/admin_shipments.apib) -->
