## Group Merchandising

The Fox Merchandising system gives users the ability to classify
products and manage the content presented with them. Like Product
Management, it is built on top of a very flexible model that allows
content to be attached to every object and for the object to exist
in multiple **contexts**.

Like Product Management, all information is automatically versioned.

<!-- include(resources/admin_albums.apib) -->
<!-- include(resources/admin_taxonomies.apib) -->
