## Group Product Management

Managing products, their attributes, and how they are sold is one of
core aspects of the Fox Platform. The principle characteristic of
products management inside Fox is flexiblity around the definition
and implemenation of what a product should have. Aside from a few
key fields, as an admin, you have the ability to make products fit
your usecase like a glove.

All information is stored in a specific **context**
and every change is automatically versioned.

In addition, each of the core objects (Products and SKUs) may be
classified by tags and taxonomies.

<!-- include(resources/admin_products.apib) -->
<!-- include(resources/admin_skus.apib) -->
<!-- include(resources/admin_variants.apib) -->
