# Storefront

Storefront related endpoints (requires customer authentication).

<!-- include(objects/common.apib) -->
<!-- include(objects/credit_cards.apib) -->
<!-- include(objects/customers.apib) -->
<!-- include(objects/gift_card.apib) -->
<!-- include(objects/location.apib) -->
<!-- include(objects/order.apib) -->
<!-- include(objects/save_for_later.apib) -->
<!-- include(objects/store_credit.apib) -->

## Group Account

Account management endpoints.

<!-- include(resources/customer_account.apib) -->

## Group Addresses

Address management endpoints.

<!-- include(resources/customer_addresses.apib) -->

## Group Cart

Cart management endpoints.

<!-- include(resources/customer_cart.apib) -->

## Group Credit Cards

Credit Cards management endpoints.

<!-- include(resources/customer_credit_cards.apib) -->

## Group Orders

Orders management endpoints.

<!-- include(resources/customer_orders.apib) -->

## Group Save For Later

Save For Later management endpoints.

<!-- include(resources/customer_save_for_later.apib) -->

## Group Store Credits

Store Credits management endpoints.

<!-- include(resources/customer_store_credits.apib) -->
