## Group Order Management

The Fox Platform allows for robust handling of customer purchases, allowing
administrators, customer service representatives, and others to work with carts,
place orders, and manage payment methods.

<!-- include(resources/admin_carts.apib) -->
<!-- include(resources/admin_orders.apib) -->

## Group Payments

The Fox Platform supports three main ways to pay for products purchased on
supported sites: credit cards, gift cards, and store credit. Credit card
processing is handled through Stripe, while gift cards and store credit is built
deeply into the platform.

<!-- include(resources/admin_gift_cards.apib) -->
<!-- include(resources/admin_store_credits.apib) -->

## Group Export

Entities export endpoint.

<!-- include(resources/admin_export.apib) -->
