require('rubygems')
require('json')
require('yaml')
require('open-uri')

desc "download babel-browser"
task :fetch_remotes do
  IO.copy_stream(
    open('https://unpkg.com/babel-standalone@6.15.0/babel.min.js'),
    'js/babel.min.js'
  )
end

desc "generate js from jsx"
task :js do
  system "./node_modules/.bin/babel _js --out-dir=js"
end

desc "watch js"
task :watch do
  Process.spawn "./node_modules/.bin/babel _js --out-dir=js --watch"
  Process.waitall
end

desc "update version to match ../package.json"
task :update_version do
  react_version = JSON.parse(File.read('../package.json'))['version']
  site_config = YAML.load_file('_config.yml')
  if site_config['react_version'] != react_version
    site_config['react_version'] = react_version
    File.open('_config.yml', 'w+') { |f| f.write(site_config.to_yaml) }
  end
end

task :default => [:js]
