account_file         = "foxcomm-staging.json"
gce_project          = "foxcomm-staging"
region               = "us-central1"
appliance_image      = "appliance-base-170207-004420"
consul_leader        = "10.240.0.10"
