## Variants [/v1/variants/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a product is viewable.
    + id: `1` (required, number) - Unique indentifier for a Variant.

### View [GET]

+ Response 200 (application/json)
  + Attributes (VariantResponse)

### Create [POST /v1/variants/{context}]

+ Parameters
    + context: `default` (required, string) - The context in which a product is viewable.
+ Request (application/json)
    + Attributes (VariantPayload)
+ Response 200 (application/json)
  + Attributes (VariantResponse)

### Update [PATCH /v1/variants/{context}/{id}]

+ Parameters
    + context: `default` (required, string) - The context in which a product is viewable.
    + id: `1` (required, number) - Unique indentifier for a Variant.
+ Request (application/json)
    + Attributes (VariantPayload)
+ Response 200 (application/json)
  + Attributes (VariantResponse)
