### Login [POST /v1/public/login]

+ Request (application/json)
	+ Attributes (LoginPayload)
+ Response 200 (application/json)
    + Attributes (LoginResponse)

### Logout [POST /v1/public/logout]

+ Request (application/json)
+ Response 200 (application/json)

### Registration [POST /v1/public/registrations/new]

+ Request (application/json)
	+ Attributes (CustomerCreatePayload)
+ Response 200 (application/json)
    + Attributes (CustomerResponse)
