account_file    = "foxcomm-staging.json"
gce_project     = "foxcomm-staging"
region          = "us-central1"
zone            = "us-central1-a"
datacenter      = "swarm"
network         = "default"
bucket_location = "us"

base_image      = "swarm-base-161102-143743"
master_image    = "swarm-master-161102-144619"
worker_image    = "swarm-worker-161102-144630"
masters_count   = "3"
workers_count   = "2"
