account_file    = "foxcomm-staging.json"
gce_project     = "foxcomm-staging"
region          = "us-central1"
zone            = "us-central1-a"
datacenter      = "swarm"
network         = "default"
bucket_location = "us"

base_image      = "swarm-base-161101-221346"
master_image    = "swarm-master-161101-223535"
worker_image    = "swarm-worker-161101-223539"
masters_count   = "3"
workers_count   = "2"
