create table skus (
  id serial primary key,
  scope exts.ltree not null,
  code generic_string not null,
  upc generic_string,
  unit_cost integer not null default 0,
  tax_class generic_string not null,
  requires_shipping boolean not null default true,
  shipping_class generic_string not null,
  is_returnable boolean not null default true,
  return_window_value decimal,
  return_window_units generic_string,
  height_value decimal,
  height_units generic_string,
  weight_value decimal,
  weight_units generic_string,
  length_value decimal,
  length_units generic_string,
  width_value decimal,
  width_units generic_string,
  requires_inventory_tracking boolean not null default true,
  inventory_warning_level_is_enabled boolean not null default false,
  inventory_warning_level_value integer,
  maximum_quantity_in_cart_is_enabled boolean not null default false,
  maximum_quantity_in_cart_value integer,
  minimum_quantity_in_cart_is_enabled boolean not null default false,
  minimum_quantity_in_cart_value integer,
  allow_backorder boolean not null default false,
  allow_preorder boolean not null default false,
  requires_lot_tracking boolean not null default false,
  lot_expiration_threshold_value decimal,
  lot_expiration_threshold_units generic_string,
  lot_expiration_warning_threshold_value decimal,
  lot_expiration_warning_threshold_units generic_string
);


