account_file = "foxcomm-vanilla.json"
gce_project  = "foxcommerce-production-shared"
region       = "us-central1"
zone         = "us-central1-a"
vpn_image    = "ubuntu-1604-xenial-v20160921"
network      = "tpg"
datacenter   = "tpg"
