clean:
	sbt clean

build:
	@echo "--- Building \033[33mintegration-tests\033[0m"
	sbt gatling:compile

test:
	@echo "--- Testing \033[33mintegration-tests\033[0m"
	true

docker:
	@echo "--- Dockerizing \033[33mintegration-tests\033[0m"
	true

docker-push:
	@echo "--- Registering \033[33mintegration-tests\033[0m"
	true

.PHONY: build clean test docker docker-push
