account_file       = "foxcomm-vanilla.json"
gce_project        = "foxcommerce-production-shared"
network            = "tpg"
region             = "us-central1"
zone               = "us-central1-a"
nano_amigo_image   = "nanostack-amigo-1477907784"
nano_storage_image = "nanostack-storage-1477905775"
nano_worker_image  = "nanostack-worker-1477904373"
