insert into countries (name, alpha2, alpha3, continent, currency, languages, postal_code, code) values ('Andorra','AD','AND','Europe','EUR','{"ca"}',true,'376'),
('United Arab Emirates','AE','ARE','Asia','AED','{"ar"}',false,'971'),
('Afghanistan','AF','AFG','Asia','AFN','{"ps","uz","tk"}',true,'093'),
('Antigua and Barbuda','AG','ATG','North America','XCD','{"en"}',false,'001'),
('Anguilla','AI','AIA','North America','XCD','{"en"}',true,'001'),
('Albania','AL','ALB','Europe','ALL','{"sq"}',true,'355'),
('Armenia','AM','ARM','Asia','AMD','{"hy","ru"}',true,'374'),
('Netherlands Antilles','AN','ANT','North America','ANG','{"nl","en"}',false,'599'),
('Angola','AO','AGO','Africa','AOA','{"pt"}',false,'244'),
('Antarctica','AQ','ATA','Antarctica','USD','{"en"}',true,'672'),
('Argentina','AR','ARG','South America','ARS','{"es","gn"}',true,'054'),
('American Samoa','AS','ASM','Australia','USD','{"en","sm"}',true,'001'),
('Austria','AT','AUT','Europe','EUR','{"de"}',true,'043'),
('Australia','AU','AUS','Australia','AUD','{"en"}',true,'061'),
('Aruba','AW','ABW','North America','AWG','{"nl"}',false,'297'),
('Åland Islands','AX','ALA','Europe','USD','{"sv"}',true,'358'),
('Azerbaijan','AZ','AZE','Asia','AZN','{"az","hy"}',true,'994'),
('Bosnia and Herzegovina','BA','BIH','Europe','BAM','{"bs","hr","sr"}',true,'387'),
('Barbados','BB','BRB','North America','BBD','{"en"}',true,'001'),
('Bangladesh','BD','BGD','Asia','BDT','{"bn"}',true,'880'),
('Belgium','BE','BEL','Europe','EUR','{"nl","fr","de"}',true,'032'),
('Burkina Faso','BF','BFA','Africa','XOF','{"fr","ff"}',false,'226'),
('Bulgaria','BG','BGR','Europe','BGN','{"bg"}',true,'359'),
('Bahrain','BH','BHR','Asia','BHD','{"ar"}',true,'973'),
('Burundi','BI','BDI','Africa','BIF','{"fr","rn"}',false,'257'),
('Benin','BJ','BEN','Africa','XOF','{"fr"}',false,'229'),
('Saint Barthélemy','BL','BLM','North America','EUR','{"fr"}',true,'590'),
('Bermuda','BM','BMU','North America','BMD','{"en"}',true,'001'),
('Brunei Darussalam','BN','BRN','Asia','BND','{"ms"}',true,'673'),
('Bolivia','BO','BOL','South America','BOB','{"es","ay","qu"}',true,'591'),
('Bonaire, Sint Eustatius and Saba','BQ','BES','North America','USD','{"nl","en"}',true,'599'),
('Brazil','BR','BRA','South America','BRL','{"BR"}',true,'055'),
('Bahamas','BS','BHS','North America','BSD','{"en"}',false,'001'),
('Bhutan','BT','BTN','Asia','BTN','{"dz"}',true,'975'),
('Bouvet Island','BV','BVT','Antarctica','NOK','{"en"}',true,null),
('Botswana','BW','BWA','Africa','BWP','{"en","tn"}',false,'267'),
('Belarus','BY','BLR','Europe','BYR','{"be","ru"}',true,'375'),
('Belize','BZ','BLZ','North America','BZD','{"en","es"}',false,'501'),
('Canada','CA','CAN','North America','CAD','{"en","fr"}',true,'001'),
('Cocos (Keeling) Islands','CC','CCK','Asia','AUD','{"en"}',true,'061'),
('Congo, The Democratic Republic Of The','CD','COD','Africa','USD','{"fr","ln","kg","sw","lu"}',false,'243'),
('Central African Republic','CF','CAF','Africa','XAF','{"fr","sg"}',false,'236'),
('Congo','CG','COG','Africa','USD','{"fr","ln"}',false,'242'),
('Switzerland','CH','CHE','Europe','CHF','{"de","fr","it"}',true,'041'),
('Côte D''Ivoire','CI','CIV','Africa','XOF','{"fr"}',false,'225'),
('Cook Islands','CK','COK','Australia','NZD','{"en"}',false,'682'),
('Chile','CL','CHL','South America','CLP','{"es"}',true,'056'),
('Cameroon','CM','CMR','Africa','XAF','{"en","fr"}',false,'237'),
('China','CN','CHN','Asia','CNY','{"zh"}',true,'086'),
('Colombia','CO','COL','South America','COP','{"es"}',true,'057'),
('Costa Rica','CR','CRI','North America','CRC','{"es"}',true,'506'),
('Cuba','CU','CUB','North America','CUP','{"es"}',true,'053'),
('Cape Verde','CV','CPV','Africa','CVE','{"pt"}',true,'238'),
('Curaçao','CW','CUW','North America','ANG','{"nl"}',true,'599'),
('Christmas Island','CX','CXR','Asia','AUD','{"en","zh","ms"}',true,'061'),
('Cyprus','CY','CYP','Asia','EUR','{"el","tr","hy"}',true,'357'),
('Czech Republic','CZ','CZE','Europe','CZK','{"cs","sk"}',true,'420'),
('Germany','DE','DEU','Europe','EUR','{"de"}',true,'049'),
('Djibouti','DJ','DJI','Africa','DJF','{"ar","fr"}',false,'253'),
('Denmark','DK','DNK','Europe','DKK','{"da"}',true,'045'),
('Dominica','DM','DMA','North America','XCD','{"en"}',false,'001'),
('Dominican Republic','DO','DOM','North America','DOP','{"es"}',true,'001'),
('Algeria','DZ','DZA','Africa','DZD','{"ar"}',true,'213'),
('Ecuador','EC','ECU','South America','USD','{"es"}',true,'593'),
('Estonia','EE','EST','Europe','EUR','{"et","ru"}',true,'372'),
('Egypt','EG','EGY','Africa','EGP','{"ar"}',true,'020'),
('Western Sahara','EH','ESH','Africa','MAD','{"es","fr"}',true,'212'),
('Eritrea','ER','ERI','Africa','ETB','{"en","ar","ti"}',false,'291'),
('Spain','ES','ESP','Europe','EUR','{"es"}',true,'034'),
('Ethiopia','ET','ETH','Africa','ETB','{"am"}',true,'251'),
('Finland','FI','FIN','Europe','EUR','{"fi","sv"}',true,'358'),
('Fiji','FJ','FJI','Australia','USD','{"en","fj","hi","ur"}',false,'679'),
('Falkland Islands (Malvinas)','FK','FLK','South America','FKP','{"en"}',true,'500'),
('Micronesia, Federated States Of','FM','FSM','Australia','USD','{"en"}',true,'691'),
('Faroe Islands','FO','FRO','Europe','DKK','{"fo"}',true,'298'),
('France','FR','FRA','Europe','EUR','{"fr"}',true,'033'),
('Gabon','GA','GAB','Africa','XAF','{"fr"}',true,'241'),
('United Kingdom','GB','GBR','Europe','GBP','{"en"}',true,'044'),
('Grenada','GD','GRD','North America','XCD','{"en"}',false,'001'),
('Georgia','GE','GEO','Asia','GEL','{"ka"}',true,'995'),
('French Guiana','GF','GUF','South America','EUR','{"fr"}',true,'594'),
('Guernsey','GG','GGY','Europe','GBP','{"en","fr"}',true,'044'),
('Ghana','GH','GHA','Africa','GHS','{"en"}',false,'233'),
('Gibraltar','GI','GIB','Europe','GIP','{"en"}',true,'350'),
('Greenland','GL','GRL','North America','DKK','{"kl"}',true,'299'),
('Gambia','GM','GMB','Africa','GMD','{"en"}',false,'220'),
('Guinea','GN','GIN','Africa','GNF','{"fr","ff"}',false,'224'),
('Guadeloupe','GP','GLP','North America','EUR','{"fr"}',true,'590'),
('Equatorial Guinea','GQ','GNQ','Africa','USD','{"es","fr"}',false,'240'),
('Greece','GR','GRC','Europe','EUR','{"el"}',true,'030'),
('South Georgia and the South Sandwich Islands','GS','SGS','Antarctica','USD','{"en"}',true,'500'),
('Guatemala','GT','GTM','North America','GTQ','{"es"}',true,'502'),
('Guam','GU','GUM','Australia','USD','{"en","ch","es"}',true,'001'),
('Guinea-Bissau','GW','GNB','Africa','XOF','{"pt"}',true,'245'),
('Guyana','GY','GUY','South America','GYD','{"en"}',false,'592'),
('Hong Kong','HK','HKG','Asia','HKD','{"en","zh"}',false,'852'),
('Heard and McDonald Islands','HM','HMD','Antarctica','AUD','{"en"}',true,null),
('Honduras','HN','HND','North America','HNL','{"es"}',true,'504'),
('Croatia','HR','HRV','Europe','HRK','{"hr"}',true,'385'),
('Haiti','HT','HTI','North America','USD','{"fr","ht"}',true,'509'),
('Hungary','HU','HUN','Europe','HUF','{"hu"}',true,'036'),
('Indonesia','ID','IDN','Asia','IDR','{"id"}',true,'062'),
('Ireland','IE','IRL','Europe','EUR','{"en","ga"}',false,'353'),
('Israel','IL','ISR','Asia','ILS','{"he","ar"}',true,'972'),
('Isle of Man','IM','IMN','Europe','IMP','{"en","gv"}',true,'044'),
('India','IN','IND','Asia','INR','{"hi","en"}',true,'091'),
('British Indian Ocean Territory','IO','IOT','Asia','USD','{"en"}',true,'246'),
('Iraq','IQ','IRQ','Asia','IQD','{"ar"}',true,'964'),
('Iran, Islamic Republic Of','IR','IRN','Asia','IRR','{"fa"}',true,'098'),
('Iceland','IS','ISL','Europe','ISK','{"is"}',true,'354'),
('Italy','IT','ITA','Europe','EUR','{"it"}',true,'039'),
('Jersey','JE','JEY','Europe','JEP','{"en","fr"}',true,'044'),
('Jamaica','JM','JAM','North America','JMD','{"en"}',false,'001'),
('Jordan','JO','JOR','Asia','JOD','{"ar"}',true,'962'),
('Japan','JP','JPN','Asia','JPY','{"ja"}',true,'081'),
('Kenya','KE','KEN','Africa','KES','{"en","sw"}',false,'254'),
('Kyrgyzstan','KG','KGZ','Asia','KGS','{"ky","ru"}',true,'996'),
('Cambodia','KH','KHM','Asia','KHR','{"km"}',true,'855'),
('Kiribati','KI','KIR','Australia','AUD','{"en"}',false,'686'),
('Comoros','KM','COM','Africa','KMF','{"ar","fr"}',false,'269'),
('Saint Kitts And Nevis','KN','KNA','North America','XCD','{"en"}',false,'001'),
('Korea, Democratic People''s Republic Of','KP','PRK','Asia','KPW','{"ko"}',false,'850'),
('Korea, Republic of','KR','KOR','Asia','KRW','{"ko"}',true,'082'),
('Kuwait','KW','KWT','Asia','KWD','{"ar"}',true,'965'),
('Cayman Islands','KY','CYM','North America','KYD','{"en"}',true,'001'),
('Kazakhstan','KZ','KAZ','Asia','KZT','{"kk","ru"}',true,'007'),
('Lao People''s Democratic Republic','LA','LAO','Asia','LAK','{"lo"}',true,'856'),
('Lebanon','LB','LBN','Asia','LBP','{"ar","fr"}',true,'961'),
('Saint Lucia','LC','LCA','North America','XCD','{"en"}',false,'001'),
('Liechtenstein','LI','LIE','Europe','CHF','{"de"}',true,'423'),
('Sri Lanka','LK','LKA','Asia','LKR','{"si","ta"}',true,'094'),
('Liberia','LR','LBR','Africa','LRD','{"en"}',true,'231'),
('Lesotho','LS','LSO','Africa','LSL','{"en","st"}',true,'266'),
('Lithuania','LT','LTU','Europe','EUR','{"lt"}',true,'370'),
('Luxembourg','LU','LUX','Europe','EUR','{"fr","de","lb"}',true,'352'),
('Latvia','LV','LVA','Europe','EUR','{"lv"}',true,'371'),
('Libya','LY','LBY','Africa','LYD','{"ar"}',true,'218'),
('Morocco','MA','MAR','Africa','MAD','{"ar"}',true,'212'),
('Monaco','MC','MCO','Europe','EUR','{"fr"}',true,'377'),
('Moldova, Republic of','MD','MDA','Europe','MDL','{"ro"}',true,'373'),
('Montenegro','ME','MNE','Europe','EUR','{"sr","bs","sq","hr"}',true,'382'),
('Saint Martin','MF','MAF','North America','EUR','{"en","fr","nl"}',true,'590'),
('Madagascar','MG','MDG','Africa','USD','{"fr","mg"}',true,'261'),
('Marshall Islands','MH','MHL','Australia','USD','{"en","mh"}',true,'692'),
('Macedonia, the Former Yugoslav Republic Of','MK','MKD','Europe','MKD','{"mk"}',true,'389'),
('Mali','ML','MLI','Africa','XOF','{"fr"}',false,'223'),
('Myanmar','MM','MMR','Asia','MMK','{"my"}',true,'095'),
('Mongolia','MN','MNG','Asia','MNT','{"mn"}',true,'976'),
('Macao','MO','MAC','Asia','USD','{"zh","pt"}',false,'853'),
('Northern Mariana Islands','MP','MNP','Australia','USD','{"en","ch"}',true,'001'),
('Martinique','MQ','MTQ','North America','EUR','{"fr"}',true,'596'),
('Mauritania','MR','MRT','Africa','MRO','{"ar","fr"}',false,'222'),
('Montserrat','MS','MSR','North America','XCD','{"en"}',false,'001'),
('Malta','MT','MLT','Europe','EUR','{"mt","en"}',true,'356'),
('Mauritius','MU','MUS','Africa','MUR','{"en"}',false,'230'),
('Maldives','MV','MDV','Asia','MVR','{"dv"}',true,'960'),
('Malawi','MW','MWI','Africa','MWK','{"en","ny"}',false,'265'),
('Mexico','MX','MEX','North America','MXN','{"es"}',true,'052'),
('Malaysia','MY','MYS','Asia','MYR','{"ms","en"}',true,'060'),
('Mozambique','MZ','MOZ','Africa','MZN','{"pt"}',true,'258'),
('Namibia','NA','NAM','Africa','NAD','{"en","af"}',true,'264'),
('New Caledonia','NC','NCL','Australia','XPF','{"fr"}',true,'687'),
('Niger','NE','NER','Africa','XOF','{"fr"}',true,'227'),
('Norfolk Island','NF','NFK','Australia','AUD','{"en"}',true,'672'),
('Nigeria','NG','NGA','Africa','NGN','{"en"}',true,'234'),
('Nicaragua','NI','NIC','North America','NIO','{"es"}',true,'505'),
('Netherlands','NL','NLD','Europe','EUR','{"nl"}',true,'031'),
('Norway','NO','NOR','Europe','NOK','{"nb","nn"}',true,'047'),
('Nepal','NP','NPL','Asia','NPR','{"ne"}',true,'977'),
('Nauru','NR','NRU','Australia','AUD','{"en","na"}',false,'674'),
('Niue','NU','NIU','Australia','USD','{"en"}',false,'683'),
('New Zealand','NZ','NZL','Australia','NZD','{"en"}',true,'064'),
('Oman','OM','OMN','Asia','OMR','{"ar"}',true,'968'),
('Panama','PA','PAN','North America','PAB','{"es"}',false,'507'),
('Peru','PE','PER','South America','PEN','{"es"}',true,'051'),
('French Polynesia','PF','PYF','Australia','XPF','{"fr"}',true,'689'),
('Papua New Guinea','PG','PNG','Australia','PGK','{"en"}',true,'675'),
('Philippines','PH','PHL','Asia','PHP','{"tl","en"}',true,'063'),
('Pakistan','PK','PAK','Asia','PKR','{"en","ur"}',true,'092'),
('Poland','PL','POL','Europe','PLN','{"pl"}',true,'048'),
('Saint Pierre And Miquelon','PM','SPM','North America','EUR','{"fr"}',true,'508'),
('Pitcairn','PN','PCN','Australia','NZD','{"en"}',true,null),
('Puerto Rico','PR','PRI','North America','USD','{"es","en"}',true,'001'),
('Palestine, State of','PS','PSE','Asia','USD','{"ar","he","en"}',true,'970'),
('Portugal','PT','PRT','Europe','EUR','{"pt"}',true,'351'),
('Palau','PW','PLW','Australia','USD','{"en"}',true,'680'),
('Paraguay','PY','PRY','South America','PYG','{"es","gn"}',true,'595'),
('Qatar','QA','QAT','Asia','QAR','{"ar"}',false,'974'),
('Réunion','RE','REU','Africa','EUR','{"fr"}',true,'262'),
('Romania','RO','ROU','Europe','RON','{"ro"}',true,'040'),
('Serbia','RS','SRB','Europe','RSD','{"sr"}',true,'381'),
('Russian Federation','RU','RUS','Europe','RUB','{"ru"}',true,'007'),
('Rwanda','RW','RWA','Africa','RWF','{"rw","en","fr"}',false,'250'),
('Saudi Arabia','SA','SAU','Asia','SAR','{"ar"}',false,'966'),
('Solomon Islands','SB','SLB','Australia','SBD','{"en"}',false,'677'),
('Seychelles','SC','SYC','Africa','SCR','{"fr","en"}',false,'248'),
('Sudan','SD','SDN','Africa','SDG','{"ar","en"}',true,'249'),
('Sweden','SE','SWE','Europe','SEK','{"sv"}',true,'046'),
('Singapore','SG','SGP','Asia','SGD','{"en","ms","ta"}',true,'065'),
('Saint Helena','SH','SHN','Africa','SHP','{"en"}',true,'290'),
('Slovenia','SI','SVN','Europe','EUR','{"sl"}',true,'386'),
('Svalbard And Jan Mayen','SJ','SJM','Europe','NOK','{"no"}',true,'047'),
('Slovakia','SK','SVK','Europe','EUR','{"sk"}',true,'421'),
('Sierra Leone','SL','SLE','Africa','SLL','{"en"}',false,'232'),
('San Marino','SM','SMR','Europe','EUR','{"it"}',true,'378'),
('Senegal','SN','SEN','Africa','XOF','{"fr"}',true,'221'),
('Somalia','SO','SOM','Africa','SOS','{"so","ar"}',false,'252'),
('Suriname','SR','SUR','South America','SRD','{"nl"}',false,'597'),
('South Sudan','SS','SSD','Africa','SSP','{"ar","en"}',true,'211'),
('Sao Tome and Principe','ST','STP','Africa','STD','{"pt"}',false,'239'),
('El Salvador','SV','SLV','North America','USD','{"es"}',true,'503'),
('Sint Maarten','SX','SXM','North America','ANG','{"nl","en"}',true,'001'),
('Syrian Arab Republic','SY','SYR','Asia','SYP','{"ar"}',false,'963'),
('Swaziland','SZ','SWZ','Africa','SZL','{"en","ss"}',true,'268'),
('Turks and Caicos Islands','TC','TCA','North America','USD','{"en"}',true,'001'),
('Chad','TD','TCD','Africa','XAF','{"ar","fr"}',true,'235'),
('French Southern Territories','TF','ATF','Antarctica','EUR','{"fr"}',false,null),
('Togo','TG','TGO','Africa','XOF','{"fr"}',true,'228'),
('Thailand','TH','THA','Asia','THB','{"th"}',true,'066'),
('Tajikistan','TJ','TJK','Asia','TJS','{"tg","ru"}',true,'992'),
('Tokelau','TK','TKL','Australia','NZD','{"en"}',false,'690'),
('Timor-Leste','TL','TLS','Asia','IDR','{"pt"}',false,'670'),
('Turkmenistan','TM','TKM','Asia','TMT','{"tk","ru"}',true,'993'),
('Tunisia','TN','TUN','Africa','TND','{"ar","fr"}',true,'216'),
('Tonga','TO','TON','Australia','TOP','{"en","to"}',false,'676'),
('Turkey','TR','TUR','Europe','TRY','{"tr"}',true,'090'),
('Trinidad and Tobago','TT','TTO','North America','TTD','{"en"}',false,'001'),
('Tuvalu','TV','TUV','Australia','TVD','{"en"}',false,'688'),
('Taiwan, Republic Of China','TW','TWN','Asia','TWD','{"zh"}',true,'886'),
('Tanzania, United Republic of','TZ','TZA','Africa','TZS','{"sw","en"}',false,'255'),
('Ukraine','UA','UKR','Europe','UAH','{"uk"}',true,'380'),
('Uganda','UG','UGA','Africa','UGX','{"en","sw"}',false,'256'),
('United States Minor Outlying Islands','UM','UMI','Australia','USD','{"en"}',true,null),
('United States','US','USA','North America','USD','{"en"}',true,'001'),
('Uruguay','UY','URY','South America','UYU','{"es"}',true,'598'),
('Uzbekistan','UZ','UZB','Asia','UZS','{"uz","ru"}',true,'998'),
('Holy See (Vatican City State)','VA','VAT','Europe','EUR','{"it","la"}',true,'039'),
('Saint Vincent And The Grenedines','VC','VCT','North America','XCD','{"en"}',true,'001'),
('Venezuela, Bolivarian Republic of','VE','VEN','South America','VEF','{"es"}',true,'058'),
('Virgin Islands, British','VG','VGB','North America','USD','{"en"}',true,'001'),
('Virgin Islands, U.S.','VI','VIR','North America','USD','{"en"}',true,'001'),
('Vietnam','VN','VNM','Asia','VND','{"vi"}',true,'084'),
('Vanuatu','VU','VUT','Australia','USD','{"bi","en","fr"}',false,'678'),
('Wallis and Futuna','WF','WLF','Australia','XPF','{"fr"}',true,'681'),
('Samoa','WS','WSM','Australia','USD','{"sm","en"}',true,'685'),
('Yemen','YE','YEM','Asia','YER','{"ar"}',false,'967'),
('Mayotte','YT','MYT','Africa','EUR','{"fr"}',true,'262'),
('South Africa','ZA','ZAF','Africa','ZAR','{"af","en","nr","st","ss","tn","ts","ve","xh","zu"}',false,'027'),
('Zambia','ZM','ZMB','Africa','ZMK','{"en"}',true,'260'),
('Zimbabwe','ZW','ZWE','Africa','ZWD','{"en","sn","nd"}',false,'263');

